// @generated by protoc-gen-connect-es v0.11.0 with parameter "target=ts"
// @generated from file chat/chat.proto (package chat, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ReadMessagesRequest, ReadMessagesResponse, WriteMessageRequest, WriteMessageResponse } from "./chat_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service chat.DiscordService
 */
export const DiscordService = {
  typeName: "chat.DiscordService",
  methods: {
    /**
     * @generated from rpc chat.DiscordService.ReadMessages
     */
    readMessages: {
      name: "ReadMessages",
      I: ReadMessagesRequest,
      O: ReadMessagesResponse,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * @generated from rpc chat.DiscordService.WriteMessage
     */
    writeMessage: {
      name: "WriteMessage",
      I: WriteMessageRequest,
      O: WriteMessageResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

