// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/google/uuid"
	"github.com/lunabrain-ai/lunabrain/pkg/incubator/ent/content"
	"github.com/lunabrain-ai/lunabrain/pkg/incubator/ent/group"
	"github.com/lunabrain-ai/lunabrain/pkg/incubator/ent/groupuser"
	"github.com/lunabrain-ai/lunabrain/pkg/incubator/ent/schema"
	"github.com/lunabrain-ai/lunabrain/pkg/incubator/ent/tag"
	entuser "github.com/lunabrain-ai/lunabrain/pkg/incubator/ent/user"
	"github.com/lunabrain-ai/lunabrain/pkg/incubator/ent/vote"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	contentFields := schema.Content{}.Fields()
	_ = contentFields
	// contentDescID is the schema descriptor for id field.
	contentDescID := contentFields[0].Descriptor()
	// content.DefaultID holds the default value on creation for the id field.
	content.DefaultID = contentDescID.Default.(func() uuid.UUID)
	groupFields := schema.Group{}.Fields()
	_ = groupFields
	// groupDescID is the schema descriptor for id field.
	groupDescID := groupFields[0].Descriptor()
	// group.DefaultID holds the default value on creation for the id field.
	group.DefaultID = groupDescID.Default.(func() uuid.UUID)
	groupuserFields := schema.GroupUser{}.Fields()
	_ = groupuserFields
	// groupuserDescID is the schema descriptor for id field.
	groupuserDescID := groupuserFields[0].Descriptor()
	// groupuser.DefaultID holds the default value on creation for the id field.
	groupuser.DefaultID = groupuserDescID.Default.(func() uuid.UUID)
	tagFields := schema.Tag{}.Fields()
	_ = tagFields
	// tagDescID is the schema descriptor for id field.
	tagDescID := tagFields[0].Descriptor()
	// tag.DefaultID holds the default value on creation for the id field.
	tag.DefaultID = tagDescID.Default.(func() uuid.UUID)
	entuserFields := schema.User{}.Fields()
	_ = entuserFields
	// entuserDescID is the schema descriptor for id field.
	entuserDescID := entuserFields[0].Descriptor()
	// entuser.DefaultID holds the default value on creation for the id field.
	entuser.DefaultID = entuserDescID.Default.(func() uuid.UUID)
	voteFields := schema.Vote{}.Fields()
	_ = voteFields
	// voteDescID is the schema descriptor for id field.
	voteDescID := voteFields[0].Descriptor()
	// vote.DefaultID holds the default value on creation for the id field.
	vote.DefaultID = voteDescID.Default.(func() uuid.UUID)
}
