version: '3.6'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/db
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data/db
    labels:
      kompose.service.type: clusterip
      kompose.volume.type: persistentVolumeClaim
volumes:
  db:
