// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Content is the predicate function for content builders.
type Content func(*sql.Selector)

// Event is the predicate function for entevent builders.
type Event func(*sql.Selector)

// Group is the predicate function for group builders.
type Group func(*sql.Selector)

// GroupInvite is the predicate function for groupinvite builders.
type GroupInvite func(*sql.Selector)

// GroupUser is the predicate function for groupuser builders.
type GroupUser func(*sql.Selector)

// Session is the predicate function for session builders.
type Session func(*sql.Selector)

// Tag is the predicate function for tag builders.
type Tag func(*sql.Selector)

// User is the predicate function for entuser builders.
type User func(*sql.Selector)
