//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type ContinuityContainers struct {
	ID         uuid.UUID `sql:"primary_key"`
	IdentityID *uuid.UUID
	Name       string
	Payload    *string
	ExpiresAt  time.Time
	CreatedAt  time.Time
	UpdatedAt  time.Time
	Nid        *uuid.UUID
}
