//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type IdentityVerifiableAddresses struct {
	ID         uuid.UUID `sql:"primary_key"`
	Status     string
	Via        string
	Verified   bool
	Value      string
	VerifiedAt *time.Time
	IdentityID uuid.UUID
	CreatedAt  time.Time
	UpdatedAt  time.Time
	Nid        *uuid.UUID
}
