//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type Identities struct {
	ID             uuid.UUID `sql:"primary_key"`
	SchemaID       string
	Traits         string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Nid            *uuid.UUID
	State          string
	StateChangedAt *time.Time
}
