//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type IdentityRecoveryTokens struct {
	ID                        uuid.UUID `sql:"primary_key"`
	Token                     string
	Used                      bool
	UsedAt                    *time.Time
	IdentityRecoveryAddressID *uuid.UUID
	SelfserviceRecoveryFlowID *uuid.UUID
	CreatedAt                 time.Time
	UpdatedAt                 time.Time
	ExpiresAt                 time.Time
	IssuedAt                  time.Time
	Nid                       *uuid.UUID
	IdentityID                uuid.UUID
}
