//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type SelfserviceErrors struct {
	ID        uuid.UUID `sql:"primary_key"`
	Errors    string
	SeenAt    *time.Time
	WasSeen   bool
	CreatedAt time.Time
	UpdatedAt time.Time
	CsrfToken string
	Nid       *uuid.UUID
}
