// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type BookmarkQueryRequest struct {
	Test string `json:"test"`
}

type BookmarkQueryResponse struct {
	Test string `json:"test"`
}

type NewBookmark struct {
	URL string `json:"url"`
}

type SavedBookmark struct {
	ID    string `json:"id"`
	Title string `json:"title"`
	URL   string `json:"url"`
}
