// @generated by protoc-gen-connect-es v0.11.0 with parameter "target=ts"
// @generated from file protoflow.proto (package protoflow, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ChatRequest, ChatResponse, ConvertFileRequest, FilePath, GetSessionRequest, GetSessionResponse, GetSessionsRequest, GetSessionsResponse, OCRText, Segment, Transcription, TranscriptionRequest, YouTubeVideo } from "./protoflow_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service protoflow.ProtoflowService
 */
export const ProtoflowService = {
  typeName: "protoflow.ProtoflowService",
  methods: {
    /**
     * @generated from rpc protoflow.ProtoflowService.DownloadYouTubeVideo
     */
    downloadYouTubeVideo: {
      name: "DownloadYouTubeVideo",
      I: YouTubeVideo,
      O: FilePath,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc protoflow.ProtoflowService.GetSessions
     */
    getSessions: {
      name: "GetSessions",
      I: GetSessionsRequest,
      O: GetSessionsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc protoflow.ProtoflowService.GetSession
     */
    getSession: {
      name: "GetSession",
      I: GetSessionRequest,
      O: GetSessionResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc protoflow.ProtoflowService.Chat
     */
    chat: {
      name: "Chat",
      I: ChatRequest,
      O: ChatResponse,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * @generated from rpc protoflow.ProtoflowService.ConvertFile
     */
    convertFile: {
      name: "ConvertFile",
      I: ConvertFileRequest,
      O: FilePath,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc protoflow.ProtoflowService.OCR
     */
    oCR: {
      name: "OCR",
      I: FilePath,
      O: OCRText,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc protoflow.ProtoflowService.Transcribe
     */
    transcribe: {
      name: "Transcribe",
      I: TranscriptionRequest,
      O: Transcription,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc protoflow.ProtoflowService.LiveTranscribe
     */
    liveTranscribe: {
      name: "LiveTranscribe",
      I: TranscriptionRequest,
      O: Segment,
      kind: MethodKind.ServerStreaming,
    },
  }
} as const;

