// @generated by protoc-gen-connect-es v0.11.0 with parameter "target=ts"
// @generated from file python.proto (package python, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { Categories, CategorizeRequest, Index, IndexDirectoryRequest, IndexQuery, QueryResult, SummarizeRequest, SummarizeResponse, Text, TranscribeRequest, TranscribeResponse, Transcript, Video } from "./python_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service python.Python
 */
export const Python = {
  typeName: "python.Python",
  methods: {
    /**
     * @generated from rpc python.Python.Transcribe
     */
    transcribe: {
      name: "Transcribe",
      I: TranscribeRequest,
      O: TranscribeResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc python.Python.Summarize
     */
    summarize: {
      name: "Summarize",
      I: SummarizeRequest,
      O: SummarizeResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc python.Python.YoutubeTranscript
     */
    youtubeTranscript: {
      name: "YoutubeTranscript",
      I: Video,
      O: Transcript,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc python.Python.Normalize
     */
    normalize: {
      name: "Normalize",
      I: Text,
      O: Text,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc python.Python.Categorize
     */
    categorize: {
      name: "Categorize",
      I: CategorizeRequest,
      O: Categories,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc python.Python.IndexDirectory
     */
    indexDirectory: {
      name: "IndexDirectory",
      I: IndexDirectoryRequest,
      O: Index,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc python.Python.QueryIndex
     */
    queryIndex: {
      name: "QueryIndex",
      I: IndexQuery,
      O: QueryResult,
      kind: MethodKind.Unary,
    },
  }
} as const;

