// @generated by protoc-gen-connect-es v0.11.0 with parameter "target=ts"
// @generated from file jsonschema.proto (package jsonschema, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetPhoneNumbersRequest, GetPhoneNumbersResponse } from "./jsonschema_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service jsonschema.PhoneNumbers
 */
export const PhoneNumbers = {
  typeName: "jsonschema.PhoneNumbers",
  methods: {
    /**
     * @generated from rpc jsonschema.PhoneNumbers.GetPhoneNumbers
     */
    getPhoneNumbers: {
      name: "GetPhoneNumbers",
      I: GetPhoneNumbersRequest,
      O: GetPhoneNumbersResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

