# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import python_pb2 as python__pb2


class PythonStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Transcribe = channel.unary_unary(
                '/python.Python/Transcribe',
                request_serializer=python__pb2.TranscribeRequest.SerializeToString,
                response_deserializer=python__pb2.TranscribeResponse.FromString,
                )
        self.Summarize = channel.unary_unary(
                '/python.Python/Summarize',
                request_serializer=python__pb2.SummarizeRequest.SerializeToString,
                response_deserializer=python__pb2.SummarizeResponse.FromString,
                )
        self.YoutubeTranscript = channel.unary_unary(
                '/python.Python/YoutubeTranscript',
                request_serializer=python__pb2.Video.SerializeToString,
                response_deserializer=python__pb2.Transcript.FromString,
                )
        self.Normalize = channel.unary_unary(
                '/python.Python/Normalize',
                request_serializer=python__pb2.Text.SerializeToString,
                response_deserializer=python__pb2.Text.FromString,
                )


class PythonServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Transcribe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Summarize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def YoutubeTranscript(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Normalize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PythonServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Transcribe': grpc.unary_unary_rpc_method_handler(
                    servicer.Transcribe,
                    request_deserializer=python__pb2.TranscribeRequest.FromString,
                    response_serializer=python__pb2.TranscribeResponse.SerializeToString,
            ),
            'Summarize': grpc.unary_unary_rpc_method_handler(
                    servicer.Summarize,
                    request_deserializer=python__pb2.SummarizeRequest.FromString,
                    response_serializer=python__pb2.SummarizeResponse.SerializeToString,
            ),
            'YoutubeTranscript': grpc.unary_unary_rpc_method_handler(
                    servicer.YoutubeTranscript,
                    request_deserializer=python__pb2.Video.FromString,
                    response_serializer=python__pb2.Transcript.SerializeToString,
            ),
            'Normalize': grpc.unary_unary_rpc_method_handler(
                    servicer.Normalize,
                    request_deserializer=python__pb2.Text.FromString,
                    response_serializer=python__pb2.Text.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'python.Python', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Python(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Transcribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/python.Python/Transcribe',
            python__pb2.TranscribeRequest.SerializeToString,
            python__pb2.TranscribeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Summarize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/python.Python/Summarize',
            python__pb2.SummarizeRequest.SerializeToString,
            python__pb2.SummarizeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def YoutubeTranscript(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/python.Python/YoutubeTranscript',
            python__pb2.Video.SerializeToString,
            python__pb2.Transcript.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Normalize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/python.Python/Normalize',
            python__pb2.Text.SerializeToString,
            python__pb2.Text.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
