// @generated by protoc-gen-connect-es v1.3.0 with parameter "target=ts"
// @generated from file content/content.proto (package content, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { Content, ContentIDs, Contents, GetSourcesRequest, InferRequest, InferResponse, Query, RelateRequest, Results, SetTagsRequest, Sources, TagRequest, Tags, TypesResponse, VoiceInputRequest, VoiceInputResponse } from "./content_pb.js";
import { Empty, MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service content.ContentService
 */
export const ContentService = {
  typeName: "content.ContentService",
  methods: {
    /**
     * @generated from rpc content.ContentService.Save
     */
    save: {
      name: "Save",
      I: Contents,
      O: ContentIDs,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc content.ContentService.Search
     */
    search: {
      name: "Search",
      I: Query,
      O: Results,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc content.ContentService.Relate
     */
    relate: {
      name: "Relate",
      I: RelateRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc content.ContentService.Analyze
     */
    analyze: {
      name: "Analyze",
      I: Content,
      O: Contents,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc content.ContentService.Delete
     */
    delete: {
      name: "Delete",
      I: ContentIDs,
      O: ContentIDs,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc content.ContentService.GetTags
     */
    getTags: {
      name: "GetTags",
      I: TagRequest,
      O: Tags,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc content.ContentService.SetTags
     */
    setTags: {
      name: "SetTags",
      I: SetTagsRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc content.ContentService.Publish
     */
    publish: {
      name: "Publish",
      I: ContentIDs,
      O: ContentIDs,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc content.ContentService.GetSources
     */
    getSources: {
      name: "GetSources",
      I: GetSourcesRequest,
      O: Sources,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc content.ContentService.Infer
     */
    infer: {
      name: "Infer",
      I: InferRequest,
      O: InferResponse,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * @generated from rpc content.ContentService.Types
     */
    types: {
      name: "Types",
      I: Empty,
      O: TypesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc content.ContentService.VoiceInput
     */
    voiceInput: {
      name: "VoiceInput",
      I: VoiceInputRequest,
      O: VoiceInputResponse,
      kind: MethodKind.ServerStreaming,
    },
  }
} as const;

